name: 📅 Event Suggestion
description: Are you interested hosting a WebdriverIO meetup or workshop? Let's get in touch!
title: "[📅 Event Suggestion]: <title>"
labels: [Event 📅, Needs Triaging ⏳]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for your interest in hosting a WebdriverIO event. This project lives from its
        community and we support events that help to grow the project's community at large.
        We are happy to provide you funds for food and drinks __after__ we have approved your proposal.

  - type: input
    id: date
    attributes:
      label: Title
      description: What's the name of the event?
      placeholder: WebdriverIO Meetup, WebdriverIO Workshop, etc.
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      description: When would you like to host the event?
      placeholder: |
        YYYY-MM-DD
    validations:
      required: true
