name: Testrunner Multiremote Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: Testrunner Multiremote Tests
    runs-on: 'ubuntu-latest'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: Link Packages
        run: pnpm run link
        shell: bash

      - name: Testrunner Multiremote Tests
        run: pnpm run test:e2e:multiremote
        shell: bash

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-testrunner-multiremote-tests-logs
          path: e2e/wdio/*.log

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
